############################################
### __              __         __    __  ### _____  _     
### \ \            / /        / /   / /  ### \  __  \ \    
###  \ \    __    / /___  ___/ /___/ /   ###  \ \__\ \ \     
###   \ \  /  \  / / __ \/ _/ / __  /    ###   \  ___/\ \    /
###    \ \/ /\ \/ / /_/ / // / /_/ /     ###    \ \    \ \___ \ 
###     \__/  \__/\____/_//_/\__,_/      ###     \_\    \_____\\
###                                      ###
###                                      ###
############################################
# Per Player World - The ultimate world creator for your server

####################
# General Settings #
####################
